# Generated by Django 4.2.6 on 2023-11-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0004_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appplant.category2')),
            ],
        ),
    ]
