# Generated by Django 4.2.6 on 2023-11-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0008_wishlistitem3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botanist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=20)),
                ('subject', models.TextField()),
                ('botanist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appplant.botanist')),
            ],
        ),
    ]
