# Generated by Django 4.2.6 on 2023-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0012_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='appplant.CartItem', to='appplant.product2'),
        ),
    ]
