# Generated by Django 4.2.6 on 2023-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0015_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='appplant.OrderItem', to='appplant.product2'),
        ),
    ]
