# Generated by Django 4.2.6 on 2024-03-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0024_servicerequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
