# Generated by Django 4.2.6 on 2024-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0026_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
