# Generated by Django 4.2.6 on 2024-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0027_botprofile_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
