# Generated by Django 4.2.6 on 2024-03-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0028_alter_botprofile_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequests',
            name='bot_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appplant.botprofile'),
        ),
    ]
