# Generated by Django 4.2.6 on 2024-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0029_alter_servicerequests_bot_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirmed'), ('complete', 'Complete'), ('reject', 'reject')], default='pending', max_length=20),
        ),
    ]
