# Generated by Django 4.2.6 on 2024-03-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0031_botanistwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botanistwork',
            name='photo',
            field=models.ImageField(upload_to='botanist_work_photos/'),
        ),
    ]
