# Generated by Django 4.2.6 on 2024-03-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0035_botanistworkk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='customer_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_botanist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appplant.botprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
