# Generated by Django 4.2.6 on 2024-03-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0036_customerphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerphoto',
            name='chosen_botanist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appplant.botprofile'),
        ),
    ]
