# Generated by Django 4.2.6 on 2024-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0037_alter_customerphoto_chosen_botanist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='images1/')),
            ],
        ),
    ]
