# Generated by Django 4.2.6 on 2024-03-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0038_itemss'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fees',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appplant.botprofile'),
        ),
    ]
