# Generated by Django 4.2.6 on 2024-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0040_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemss',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
