# Generated by Django 4.2.6 on 2024-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appplant', '0041_itemss_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
